function setCookie(name,value)
{var Days=30;var exp=new Date();exp.setTime(exp.getTime()+Days*24*60*60*1000);document.cookie=name+"="+escape(value)+";expires="+exp.toGMTString();}
function getCookie(name)
{var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");if(arr=document.cookie.match(reg))
return unescape(arr[2]);else
return null;}
function markVideo(vd,d,t,s){var textStart=Array("很烂","很烂","一般","一般","不妨一看","不妨一看","比较精彩","比较精彩","棒极了","棒极了");var id='BT'+(new Date()).getTime();$.ajax({url:"/ajax/"+vd+"&action=videoscore",success:function(obj){var a=obj;try{a.replace(/\[(\d+),(\d+),(\d+)\]/i,function($0,d,t,s){var x=parseInt(d)+parseInt(t),y=(Math.round(s/x*10)/10.0)||0;document.getElementById('MARK_B1').value=x;document.getElementById('MARK_B2').value=y;document.getElementById('MARK_B3').value=s;if(s<=0){document.getElementById("filmStarScore").innerHTML="0<i>.0</i>";document.getElementById("start").className="starB s0";}else{var ky=y.toString();ky=ky.replace(".","<i>.");ky=ky+"</i>";document.getElementById("filmStarScore").innerHTML=ky;document.getElementById("start").className="starB s"+parseInt(y,10).toString();if(parseInt(y,10)==0){var ka=0;}else{var ka=parseInt(y,10)-1;}
document.getElementById("filmStarScoreTip").innerHTML=textStart[ka]+"("+x+"评)";if(document.getElementById("renums")){document.getElementById("renums").innerHTML=x;}}});}catch(ig){}}});}
function startm(v){var textStart=Array("很烂","很烂","一般","一般","不妨一看","不妨一看","比较精彩","比较精彩","棒极了","棒极了");document.getElementById("filmStarScoreTip").innerHTML=textStart[v-1];document.getElementById("start").className="starB s"+v.toString();document.getElementById("filmStarScore").innerHTML=v+"<i>.0</i>"}
function OnStar(mid,v){if(getCookie(mid)==null){htmlobj=$.ajax({url:"/ajax/"+mid+"-"+v,async:false});setCookie(mid,"1");alert("评分成功，感谢您的参与");}else{alert("您已评分，请勿重复提交");}}
function kaifach(){var textStart=Array("很烂","很烂","一般","一般","不妨一看","不妨一看","比较精彩","比较精彩","棒极了","棒极了");var x=parseFloat(document.getElementById("MARK_B1").value);var y=parseFloat(document.getElementById("MARK_B2").value);var z=parseFloat(document.getElementById("MARK_B3").value);var ky=y.toString();if(ky.indexOf(".")<0){ky=ky+".0";}
ky=ky.replace(".","<i>.");ky=ky+"</i>";document.getElementById("filmStarScore").innerHTML=ky;document.getElementById("start").className="starB s"+parseInt(y,10).toString();if(parseInt(y,10)>0){document.getElementById("filmStarScoreTip").innerHTML=textStart[parseInt(y,10)-1]+"("+x+"评)";}else{if(z>0){document.getElementById("filmStarScoreTip").innerHTML=textStart[0]+"("+x+"评)";}else{document.getElementById("filmStarScoreTip").innerHTML="";}}}
function getSubstr(downurl){var resultStr=downurl
if(downurl.indexOf("ed2k://|file|")==0){var tmpStr=resultStr.split('|');if(tmpStr.length>3){if(tmpStr[2].length>0){resultStr=decodeURIComponent(tmpStr[2]);}}
return resultStr;}else{return resultStr;}}
$(document).ready(function(){$('.downlisttps').html('');});$(document).ready(function(){$("#cmt-input-tip .ui-input").focus(function(){$("#cmt-input-tip").hide();$("#cmt-input-bd").show();$("#cmt-input-bd .ui-textarea").focus();});$(".user-bt").each(function(){var $btn=$(this).find(".sect-btn");var $cancel=$(this).find(".cancel");var $div=$(this).find(".sect-show");$btn.click(function(){if(!checkcookie()){login_form();return false;return false;}
$.showfloatdiv({txt:'数据提交中...',cssname:'loading'});var curobj=$(this);$.get($btn.attr('data')+Id,function(r){try{r=eval('('+r+')');$.hidediv(r);if(parseInt(r.rcode)>0){curobj.hide();$div.show();$cancel.show();$cancel.attr('val',r['loveid']);}else{if(parseInt(r['yjdy'])>0){if(parseInt(r['yjdy'])==1){curobj.hide(r);$div.show();$cancel.show();}}else{login_form();return false;}}}catch(e){login_form();return false;}},'html');});$cancel.click(function(){$.showfloatdiv({txt:'数据提交中...',cssname:'loading'});var lid=$cancel.attr('val');$.get($cancel.attr('data')+lid,function(r){$.hidediv(r);if(parseInt(r.rcode)>0){$btn.show();$div.hide();}},'json');});});$("ul.rating li").each(function(i){var $title=$(this).attr("title");var $lis=$("ul.rating li");var num=$(this).index();var n=num+1;$(this).click(function(){if(hadpingfen>0){$.showfloatdiv({txt:'已经评分,请务重复评分'});$.hidediv({});}else{$.showfloatdiv({txt:'数据提交中...',cssname:'loading'});$lis.removeClass("active");$("ul.rating li:lt("+n+")").addClass("active");$("#ratewords").html($title);$.post('/index.php?s=Gold',{val:$(this).attr('val'),'id':Id},function(r){if(parseInt(r.rcode)>0){$.hidediv(r);loadstat();hadpingfen=1;}else{if(parseInt(r.rcode)==-2){hadpingfen=1;$.showfloatdiv({txt:'已经评分,请务重复评分'});$.hidediv({});}else{$.closefloatdiv();$("#innermsg").trigger('click');}}},'json');}}).hover(function(){this.myTitle=this.title;this.title="";$(this).nextAll().removeClass("active");$(this).prevAll().addClass("active");$(this).addClass("active");$("#ratewords").html($title);},function(){this.title=this.myTitle;$("ul.rating li:lt("+n+")").removeClass("hover");});});$(".rating-panle").hover(function(){$(this).find(".rating-show").show();},function(){$(this).find(".rating-show").hide();});});